### PR TITLE
Added missing fixes from arduino-dw1000 repo

### PR DESCRIPTION
**Pull request by da-phil**
The [arduino-dw1000](https://github.com/thotro/arduino-dw1000) repo - which this repo was forked from - received some fixes which have not been applied to this repo yet.
In fact, one commit (https://github.com/thotro/arduino-dw1000/commit/ea4f2b39c5b6382d160052c12c8436968f005379) even fixed an issue where all the on-board ranging corrections are added up on top of the real value instead of subtracting from it.

### CODE REVIEW

**Comment by krichardsson** [comment]
This is interesting! 
I will try it out in our system. 

By the way, there seems to be a couple of unit tests that are broken by your changes. Please let us know if you need any help fixing them.

Thanks!

**Comment by da-phil** [comment]
@krichardsson Oh yes, I saw the failed unit tests, but couldn't figure out a convenient way how to calculate the `expected` values in the test functions yet. I'll try it again when I've got time.

Regarding the indentation: I know that this should not be part of the same PR, but I just saw that you guys do a 2 space indentation, but when I looked at the code I saw mixed indentation styles, that's why I thought tabs would be the way to go. Should I change indentation back to 2 spaces and open a separate PR for it?

**Comment by krichardsson** [comment]
@da-phil Yes, please move the indentation changes into another PR. 

Thanks!

**Comment by krichardsson** [comment]
Finally merged, thanks!

**Pull request merged**
